#!/bin/sh -e

py_maj=$(python -c 'import sys; print(str(sys.version_info.major))')
py_min=$(python -c 'import sys; print(str(sys.version_info.minor))')

rm -f target/wheels/*

pyo3-pack build -i "python${py_maj}.${py_min}" --release "$@"

pip install --force $(find target/wheels -name "*cp${py_maj}${py_min}*")
