#!/bin/sh -e

pip install --no-cache-dir --upgrade \
    'pytest-benchmark[histogram]' \
    arrow \
    flask \
    gunicorn \
    hypothesis \
    ipython \
    matplotlib \
    mypy \
    pendulum \
    pip \
    psutil \
    pyo3-pack \
    pytest \
    python-rapidjson \
    pytz \
    simplejson \
    tabulate \
    ujson \
    wheel
