#!/usr/bin/bash -e

autoflake --in-place --recursive --remove-all-unused-imports --ignore-init-module-imports .
isort ./bench/*.py ./orjson.pyi ./test/*.py pydataclass pymem pysort
black ./bench/*.py ./orjson.pyi ./test/*.py pydataclass pymem pysort
mypy --ignore-missing-imports ./bench/*.py ./orjson.pyi ./test/*.py
