#!/bin/sh -e

# rustup component add llvm-tools-preview

RUSTFLAGS="-Z pgo-gen=target/pgo/pgo.profraw" ./build --target x86_64-unknown-linux-gnu

./pybench

rustup run nightly ../lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata merge -o target/pgo/pgo.profdata target/pgo/pgo.profraw

RUSTFLAGS="-Z pgo-use=target/pgo/pgo.profdata" ./build --target x86_64-unknown-linux-gnu --strip
