#!/bin/sh -e

pytest \
    --verbose \
    --benchmark-min-time=1 \
    --benchmark-max-time=5 \
    --benchmark-disable-gc \
    --benchmark-autosave \
    --benchmark-save-data \
    bench/benchmark_*
