#!/usr/bin/env python3
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

import sys
import lzma
import gc

import psutil

filename = sys.argv[1]

with lzma.open(filename, "r") as fileh:
    file_utf8 = fileh.read()

proc = psutil.Process()

lib_name = sys.argv[2]
if lib_name == "json":
    from json import dumps, loads
elif lib_name == "orjson":
    from orjson import dumps, loads
elif lib_name == "rapidjson":
    from rapidjson import dumps, loads
elif lib_name == "simplejson":
    from simplejson import dumps, loads
elif lib_name == "ujson":
    from ujson import dumps, loads
else:
    raise NotImplementedError

gc.collect()

mem_before = proc.memory_info().rss

val = loads(file_utf8)

mem_after = proc.memory_info().rss

mem_diff = mem_after - mem_before

print(f"{mem_before},{mem_diff}")
