###############################################
############ VSCode DEV Environment ###########
###############################################
FROM ghcr.io/everysk/devcontainers-base:v1.2 AS platform_vscode