#!/bin/sh -e

rm -f target/wheels/*

export CC="clang"
export CFLAGS="-O2 -fno-plt -flto=thin"
export LDFLAGS="${CFLAGS} -fuse-ld=lld -Wl,--as-needed"
export RUSTFLAGS="-C linker=clang -C link-arg=-fuse-ld=lld"

maturin build "$@"

pip install --force target/wheels/*.whl
