#!/bin/sh -e

rm -f target/wheels/*

export CC="clang"
export CFLAGS="-O2 -fno-plt -flto=thin"
export LDFLAGS="-O2 -flto=thin -fuse-ld=lld -Wl,--as-needed"
export RUSTFLAGS="-C linker=clang -C link-arg=-fuse-ld=lld"

maturin build --compatibility off -i python3 --release "$@"

pip install --force $(find target/wheels -name "*cp3*")
