#!/usr/bin/env bash

set -eou pipefail

_repo="$(dirname "$(dirname "${BASH_SOURCE[0]}")")"

bindgen \
    "${_repo}/include/yyjson/yyjson.h" \
    --size_t-is-usize \
    --disable-header-comment \
    --no-derive-copy \
    --no-derive-debug \
    --no-doc-comments \
    --no-layout-tests \
    --allowlist-function=yyjson_alc_pool_init \
    --allowlist-function=yyjson_doc_free \
    --allowlist-function=yyjson_read_opts \
    --allowlist-type=yyjson_alc \
    --allowlist-type=yyjson_arr_iter \
    --allowlist-type=yyjson_doc \
    --allowlist-type=yyjson_obj_iter \
    --allowlist-type=yyjson_read_code \
    --allowlist-type=yyjson_read_err \
    --allowlist-type=yyjson_val \
    --allowlist-var=YYJSON_READ_NOFLAG \
    --allowlist-var=YYJSON_READ_SUCCESS \
    > "${_repo}/src/yyjson.rs"
