#!/usr/bin/env bash

set -eou pipefail

yyjson_version="210302ffc108efb5547084f7ab17a93c6d1c6649"

curl -Ls -o include/yyjson/yyjson.c "https://raw.githubusercontent.com/ibireme/yyjson/${yyjson_version}/src/yyjson.c"
curl -Ls -o include/yyjson/yyjson.h "https://raw.githubusercontent.com/ibireme/yyjson/${yyjson_version}/src/yyjson.h"

sed -i 's/yyjson_api_inline void yyjson_doc_free/yyjson_api void yyjson_doc_free/g' include/yyjson/yyjson.h
sed -i 's/if (pre)/if (false)/g' include/yyjson/yyjson.c
sed -i 's/unlikely(pos == src)/false/g' include/yyjson/yyjson.c
sed -i 's/#define YYJSON_READER_DEPTH_LIMIT 0/#define YYJSON_READER_DEPTH_LIMIT 1024/g' include/yyjson/yyjson.c
