#!/usr/bin/env bash

set -eou pipefail

twine --version

tag=$(git name-rev --tags --name-only $(git rev-parse HEAD))

echo "$tag"
find "$1" || true

if [[ "$tag" == "undefined" ]]; then
    echo "not on a tag"
    exit 0
fi

twine upload --non-interactive "$1"
